# Generated by Django 2.1.5 on 2019-02-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'acteurs',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('realisateur', models.CharField(max_length=100, null=True)),
                ('affiche', models.CharField(max_length=200, null=True)),
                ('annee', models.IntegerField(max_length=4, null=True, verbose_name='année de sortie')),
            ],
            options={
                'verbose_name': 'films',
                'ordering': ['annee'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'roles',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfilm.Role'),
        ),
        migrations.AddField(
            model_name='acteurs',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfilm.Role'),
        ),
    ]
