# Generated by Django 2.1.5 on 2019-02-07 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webfilm', '0002_auto_20190207_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'acteurs',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('realisateur', models.CharField(max_length=100, null=True)),
                ('affiche', models.CharField(max_length=200, null=True)),
                ('annee', models.IntegerField(null=True, verbose_name='année de sortie')),
            ],
            options={
                'verbose_name': 'films',
                'ordering': ['annee'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfilm.Acteurs')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfilm.Films')),
            ],
            options={
                'verbose_name': 'roles',
            },
        ),
    ]
