# Generated by Django 2.1.5 on 2019-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfilm', '0004_auto_20190220_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
