# Generated by Django 2.1.5 on 2019-02-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190206_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='produits_sans_prix',
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Vendeur',
        ),
    ]
