# Generated by Django 2.1.5 on 2019-02-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190206_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='les nouvelles crêpes au rhum !!!', max_length=100),
            preserve_default=False,
        ),
    ]
