# Generated by Django 2.1.5 on 2019-02-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'article'},
        ),
    ]
